plugin_name: hierarchy-table
version: 1.0.0
protocol: v1

description: |-
  Plugin to display a Markdown table as a presentation slide, ideal
  for hierarchies or structured data.
handler_script: "index.js"
css_files:
  - "style.css"
math:
  enabled: false 
